project:
  type: website
  resources:
    - img/*


website:
  title: "Spatial Data Science across Languages"
  navbar:
    title: false
    logo: img/sdsl-logo-small.png
    repo-actions: [issue]
    left:
      - href: index.qmd
        text: Home
      - workshops.qmd
      - href: award.qmd
        text: Lorena Abad Award
      - reports.qmd
      - governance.qmd
  page-footer:
    center:
      - text: "Copyright 2025, SDSL Community"
    right:
      - icon: github
        href: "https://github.com/spatial-data-science"
  announcement:
    icon: trophy
    dismissable: true
    content: "Nominations for the [Lorena Abad Crespo Award for Innovation in Spatial Data Science](award.qmd) are now open. [Nominate](https://docs.google.com/forms/d/e/1FAIpQLSeG_rb8Zldf-HQ_WCDhWYM2qp4NAmoGZHWXPItXQ_k2LcycVA/viewform?usp=dialog) someone!"
    type: primary
    position: below-navbar

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
